name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t widget-tests .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -e PROJECT_PUBLIC_KEY=${{ secrets.PROJECT_PUBLIC_KEY }} \
            -e API_TOKEN=${{ secrets.API_TOKEN }} \
            widget-tests
